/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CreateSender', 'model/CreateSenderModel', 'model/ErrorModel', 'model/GetIps', 'model/GetIpsFromSender', 'model/GetSendersList', 'model/UpdateSender'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CreateSender'), require('../model/CreateSenderModel'), require('../model/ErrorModel'), require('../model/GetIps'), require('../model/GetIpsFromSender'), require('../model/GetSendersList'), require('../model/UpdateSender'));
  } else {
    // Browser globals (root is window)
    if (!root.SendinBlueApi) {
      root.SendinBlueApi = {};
    }
    root.SendinBlueApi.SendersApi = factory(root.SendinBlueApi.ApiClient, root.SendinBlueApi.CreateSender, root.SendinBlueApi.CreateSenderModel, root.SendinBlueApi.ErrorModel, root.SendinBlueApi.GetIps, root.SendinBlueApi.GetIpsFromSender, root.SendinBlueApi.GetSendersList, root.SendinBlueApi.UpdateSender);
  }
}(this, function(ApiClient, CreateSender, CreateSenderModel, ErrorModel, GetIps, GetIpsFromSender, GetSendersList, UpdateSender) {
  'use strict';

  /**
   * Senders service.
   * @module api/SendersApi
   * @version 3.0.0
   */

  /**
   * Constructs a new SendersApi. 
   * @alias module:api/SendersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createSender operation.
     * @callback module:api/SendersApi~createSenderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateSenderModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new sender
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateSender} opts.sender sender&#39;s name
     * @param {module:api/SendersApi~createSenderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateSenderModel}
     */
    this.createSender = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['sender'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api-key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CreateSenderModel;

      return this.apiClient.callApi(
        '/senders', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteSender operation.
     * @callback module:api/SendersApi~deleteSenderCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a sender
     * @param {Number} senderId Id of the sender
     * @param {module:api/SendersApi~deleteSenderCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteSender = function(senderId, callback) {
      var postBody = null;

      // verify the required parameter 'senderId' is set
      if (senderId === undefined || senderId === null) {
        throw new Error("Missing the required parameter 'senderId' when calling deleteSender");
      }


      var pathParams = {
        'senderId': senderId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api-key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/senders/{senderId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getIps operation.
     * @callback module:api/SendersApi~getIpsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetIps} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all the dedicated IPs for your account
     * @param {module:api/SendersApi~getIpsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetIps}
     */
    this.getIps = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api-key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetIps;

      return this.apiClient.callApi(
        '/senders/ips', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getIpsFromSender operation.
     * @callback module:api/SendersApi~getIpsFromSenderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetIpsFromSender} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all the dedicated IPs for a sender
     * @param {Number} senderId Id of the sender
     * @param {module:api/SendersApi~getIpsFromSenderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetIpsFromSender}
     */
    this.getIpsFromSender = function(senderId, callback) {
      var postBody = null;

      // verify the required parameter 'senderId' is set
      if (senderId === undefined || senderId === null) {
        throw new Error("Missing the required parameter 'senderId' when calling getIpsFromSender");
      }


      var pathParams = {
        'senderId': senderId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api-key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetIpsFromSender;

      return this.apiClient.callApi(
        '/senders/{senderId}/ips', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSenders operation.
     * @callback module:api/SendersApi~getSendersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetSendersList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the list of all your senders
     * @param {Object} opts Optional parameters
     * @param {String} opts.ip Filter your senders for a specific ip (available for dedicated IP usage only)
     * @param {String} opts.domain Filter your senders for a specific domain
     * @param {module:api/SendersApi~getSendersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetSendersList}
     */
    this.getSenders = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'ip': opts['ip'],
        'domain': opts['domain'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api-key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetSendersList;

      return this.apiClient.callApi(
        '/senders', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSender operation.
     * @callback module:api/SendersApi~updateSenderCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a sender
     * @param {Number} senderId Id of the sender
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateSender} opts.sender sender&#39;s name
     * @param {module:api/SendersApi~updateSenderCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateSender = function(senderId, opts, callback) {
      opts = opts || {};
      var postBody = opts['sender'];

      // verify the required parameter 'senderId' is set
      if (senderId === undefined || senderId === null) {
        throw new Error("Missing the required parameter 'senderId' when calling updateSender");
      }


      var pathParams = {
        'senderId': senderId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api-key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/senders/{senderId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
